package server

// settingsSchema describes this agent's configuration sections: types,
// descriptions, defaults, ranges, and restart requirements (the Node agent's
// /settings/schema shape).
var settingsSchema = map[string]any{
	"server":           schemaServer,
	"ssl":              schemaSSL,
	"cors":             schemaCORS,
	"ui":               schemaUI,
	"startup":          schemaStartup,
	"browser":          schemaBrowser,
	"logging":          schemaLogging,
	"api_keys":         schemaAPIKeys,
	"oidc":             schemaOIDC,
	"updates":          schemaUpdates,
	"api_docs":         schemaAPIDocs,
	"stats":            schemaStats,
	"data":             schemaData,
	"database":         schemaDatabase,
	"tasks":            schemaTasks,
	"machines":         schemaMachines,
	"provisioning":     schemaProvisioning,
	"template_sources": schemaTemplateSources,
	"catalog_sources":  schemaCatalogSources,
	"artifact_storage": schemaArtifactStorage,
	"file_browser":     schemaFileBrowser,
	"guest_agent":      schemaGuestAgent,
	"snapshots":        schemaSnapshots,
	"applications":     schemaApplications,
	"ticket_system":    schemaTicketSystem,
	"cleanup":          schemaCleanup,
	"monitoring":       schemaMonitoring,
	"host_power":       schemaHostPower,
}
